services:
  # node web service
  - type: web
    name: chatgpt-dingtalk-robot
    env: node
    rootDir: .
    autoDeploy: false
    repo: https://github.com/sytpb/chatgpt-dingtalk-robot.git # optional
    region: singapore     # optional (defaults to oregon)
    plan: free            # optional (defaults to starter instance type)
    branch: beta          # optional (defaults to master)
    healthCheckPath: /healthz
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        sync: false
      - key: APPKEY
        sync: false
      - key: APPSECRET
        sync: false
      - key: OPENAI_MODEL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CHAT_HISTORY
        sync: false